# Site settings
title: facts about orange
tag_text: ORANGE
description: facts about orange, by Konstantinos Doumpenidis

# Build settings
markdown: kramdown

exclude: ["README.md"]

theme: jekyll-theme-cayman